name: nats-io
version: v2.11.8
summary: NATS Server
description: NATS is a simple, secure and performant communications system for digital systems, services and devices.
adopt-info: overlay

base: core24
confinement: strict
grade: stable

platforms:
  amd64:

apps:
  server:
    command: bin/nats-server -c $SNAP_DATA/nats-server.conf
    daemon: simple
    plugs: [network, network-bind]

parts:
  server:
    plugin: go
    source: https://github.com/nats-io/nats-server.git
    source-tag: v2.11.8
    # build-environment:
    #   - GOPROXY: https://proxy.golang.com.cn,direct
    build-snaps:
      - go
  overlay:
    plugin: dump
    source: overlay
    override-stage: |
      craftctl default
      craftctl set version="$(craftctl get version)+git$(git rev-parse --short HEAD)"
